name: CI
on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - main
      - beta
      - alpha
jobs:
  setup:
    name: Setup
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Use cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C8
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

  lint:
    name: Eslint
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Use cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C8
      - name: ESLint
        run: yarn lint
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.2.0
        if: always()
        continue-on-error: true
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          report-json: 'eslint_report.json'

  format:
    name: Prettier
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Use cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C8
      - name: Prettier
        run: yarn format:check

  build:
    name: Build and Test
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    needs: setup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Use cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}_C8
      - name: Test
        run: yarn test:coverage
      - name: Test coverage comment
        uses: MishaKav/jest-coverage-comment@main
        with:
          title: Test coverage
          summary-title: Summary
          multiple-files: |
            api-utils, ./packages/apiUtils/coverage/coverage-summary.json
            auth, ./packages/auth/coverage/coverage-summary.json
            core, ./packages/core/coverage/coverage-summary.json
            evm-utils, ./packages/evmUtils/coverage/coverage-summary.json
            evm-utils, ./packages/evmUtils/coverage/coverage-summary.json
            sol-utils, ./packages/solUtils/coverage/coverage-summary.json
            streams, ./packages/streams/coverage/coverage-summary.json
            integration, ./packages/integration/coverage/coverage-summary.json
